### ISSUE TITLE
hugoidx version

### ISSUE THREAD

**Issue by Anasme** [blevesearch/hugoidx#11]
Hello,

I like the idea of your project but i get an error when itry to launch it on my hugo website: 
`
hugoidx
ERROR: 2017/12/26 14:10:03 hugo.go:274: Current theme does not support Hugo version 0.14. Minimum version required is 0.17
ERROR: 2017/12/26 14:10:03 template.go:327: template: theme/404.html:5: function "i18n" not defined
ERROR: 2017/12/26 14:10:03 template.go:327: template: theme/_default/list.html:40: function "default" not defined
ERROR: 2017/12/26 14:10:03 template.go:327: template: theme/_default/single.html:12: function "i18n" not defined
...`

thanks for your support

**Comment by mschoch** [comment]
This project has been neglected for some time, and no longer works with any recent version of hugo.  We are archiving this project.
