### ISSUE TITLE
doc is outdated

### ISSUE THREAD

**Issue by jvermillard** [blevesearch/hugoidx#2]
I'm trying to setup this using:
http://www.blevesearch.com/news/Site-Search/

some instructions are referencing non existing files like:

```
cp $GOPATH/src/github.com/blevesearch/hugoidx/search.md content/
```

**Comment by mschoch** [comment]
I think I accidentally closed the wrong issue.  And it looks like you're right, I had planed to distribute that file, and forgot to add it.

**Comment by mschoch** [comment]
OK, I've added the file used by the bleve website, I believe it is the same as the one I had planned to distribute,  if it doesn't work, or other files are also missing please let me know.

**Comment by mukil** [comment]
Hi,
I can not find the two javascript files mentioned on that page and it would be great if you could distribute them, too!

<pre>
cp $GOPATH/src/github.com/blevesearch/hugoidx/handlebars.js static/js/
cp $GOPATH/src/github.com/blevesearch/hugoidx/search.js static/js/
</pre>

**Comment by ragingwind** [comment]
I'm hitting on same issue that missing some of files mentioned in the page of the blog. For a while, Using http://www.blevesearch.com/js/search.js instead of

**Comment by mschoch** [comment]
Sorry about that, I've just uploaded the missing files.  Let know if you find any other problems.

**Comment by mschoch** [comment]
This project has been neglected for some time, and no longer works with any recent version of hugo.  We are archiving this project.
