### ISSUE TITLE
Installing hugoidx crashes

### ISSUE THREAD

**Issue by mukil** [blevesearch/hugoidx#3]
I started to follow http://www.blevesearch.com/news/Site-Search/ but did not yet succeed with installing `hugoidx` on a Ubuntu 14.04.3 (Trusty Thar). Maybe we can figure things out together here.

I first tried to install hugoidx after installing the standard suggested go package for my ubuntu, via `sudo apt-get install gccgo-go` but that lead me to crashes like the following two:

<pre>
$ go get github.com/blevesearch/hugoidx
$ Segmentation fault (core dumped)
.. 
$ go get github.com/blevesearch/hugoidx
munmap of stack space failed: errno 22
Aborted

goroutine 1 [select]:
main.httpGET
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/http.go:29
main.bitbucketVCS
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/vcs.go:689
main.repoRootForImportPathStatic
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/vcs.go:425
main.repoRootForImportPath
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/vcs.go:360
main.downloadPackage
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/get.go:269
main.download
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/get.go:166
main.download
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/get.go:232
main.runGet
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/get.go:72
main.main
    /build/gccgo-go-8UjdDR/gccgo-go-1.2.1/src/cmd/go/main.go:161

goroutine 3 [syscall]:
    goroutine in C code; stack unavailable
</pre>

After reading that i decided to revert the previous steps and give a manual go installation a try (using go1.5.1.linux-amd64.tar.gz from https://golang.org/dl/). After setting that up i ran into the following error:

<pre>
$ go get github.com/blevesearch/hugoidx
# github.com/spf13/hugo/bufferpool
../../go-home/src/github.com/spf13/hugo/bufferpool/bufpool.go:21:24: error: reference to undefined identifier ‘sync.Pool’
 var bufferPool = &sync.Pool{
                        ^
../../go-home/src/github.com/spf13/hugo/bufferpool/bufpool.go:21:28: error: expected ‘;’ or newline after top level declaration
 var bufferPool = &sync.Pool{
                            ^
../../go-home/src/github.com/spf13/hugo/bufferpool/bufpool.go:24:2: error: expected declaration
  },
  ^
</pre>

My first guess is that my system does not meet the necessary requirements to get `hugoidx` installed. Would be great if anyone has any thoughts on how to proceed from here because i have not :) - Thanks!

**Comment by mschoch** [comment]
Can you run 'go version'?  The complaints about sync.Pool suggest you may
be running a version of go older than the package you said you downloaded.

**Comment by mukil** [comment]
Ok, sure.

<pre>
go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64
</pre>

Interesting, when i go to my custom location and start that `go` binary directly i get.

<pre>
go version go1.5.1 linux/amd64
</pre>

Despite i set the $GOROOT environment variable to my manual go installation another one seems to be called for me. Many thanks for your quick reply!

**Comment by mschoch** [comment]
Yeah I recommend you fix your path such that 'go' runs the second one.  The
first one is odd, and must be some distribution specific thing.

**Comment by mukil** [comment]
Great, done.

<pre>
$ sudo apt-get purge gccgo-go
</pre>

did the trick and to be able to execute `hugoidx` i just needed to append the `:$GOHOME/bin` directory to `$PATH` otherwise `hugoidx` would still be unknown. Now i got a `search.bleve` directory for my hugo site!

I am going to close this ticket.
Installation works for me when using a `go version go1.5.1 linux/amd64`.

Thanks for your support!
