### ISSUE TITLE
Reading from Hugo JSON pages rather than using Hugo directly

### ISSUE THREAD

**Issue by vthommeret** [blevesearch/hugoidx#6]
I tried using this tool recently and it looks like it's vendoring a fairly out-of-date version of Hugo along with some of its dependencies, so it couldn't parse my documentation. I manually updated the dependencies, but now some of the functions hugoidx was relying on are no longer public. I spent a little bit of time seeing if there was another approach, but at a high-level it doesn't seem like Hugo was designed to be called as a lib.

Recently, it's possible for Hugo to actually generate a JSON file with every page, which you can use to index a site, instead of having to call into the Hugo code:

https://discuss.gohugo.io/t/simple-json-site-index-in-hugo/2854

If you think this approach makes sense I can share a PR although I ended up writing my own tool since there's not much code (read the JSON file, add the documents) and I think most people will want to customize the indexing.

**Comment by mschoch** [comment]
Hello,

Thanks for sharing this idea, I do think it makes sense, however before we jump to a PR I think it might be useful to get the input from the Hugo community.  I spoke with Steve Francia at Gophercon and he suggested we engage with the Hugo community via their forums.  In short, my biggest question is, what is their recommended way to integrate and support it long term.  I'm fine if it's a library API, or if its a directory containing JSON.

(if you're already plugged into the Hugo community and think this is their recommended solution, just say so)

**Comment by vickychijwani** [comment]
I'm fairly new to Hugo and certainly don't use Go day-to-day, so I can't speak for the Hugo community at large, but using the JSON output to perform indexing does look like a good approach. This way hugoidx won't be coupled tightly to Hugo's implementation, as it is at this point.

@vthommeret's code could provide a good jumping off point should the maintainers decide to move forward with this approach.

**Comment by mschoch** [comment]
This project has been neglected for some time, and no longer works with any recent version of hugo.  We are archiving this project.
